### ISSUE TITLE
Error getting for "V1"

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-linter-action#21]
Steps to reproduce:
While rasing PR to execute `axe-linter-actions` on github, added `workflows/axe-linter.yml` and configured,
```
name: Linting for accessibility issues

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dequelabs/axe-linter-action@v1
        with:
          api_key: ${{ secrets.AXE_LINTER_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
based on the example given ` https://github.com/dequelabs/axe-linter-action#example-usage` but with this getting error:
![image](https://user-images.githubusercontent.com/47409579/213488535-0a0617f3-81ff-4c38-97b1-675dd30d69be.png)

Note: In the screenshot 11th line changed to `- uses: dequelabs/axe-linter-action@v1` still getting the similar error.
